# Generated by Django 3.0.5 on 2020-06-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_marker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='stripe_confirm',
            new_name='marker_id',
        ),
        migrations.AddField(
            model_name='marker',
            name='stripe_pid',
            field=models.CharField(default='TEST', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lng',
            field=models.CharField(max_length=32),
        ),
    ]
